# Generated by Django 3.2.6 on 2021-11-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('selling_price', models.FloatField(null=True)),
                ('discounted_price', models.FloatField(null=True)),
            ],
        ),
    ]
