# Generated by Django 3.2.6 on 2021-11-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TROUSER', 'Trouser'), ('SUIT', 'suit'), ('SHORT', 'short'), ('SHIRT', 'shirt')], default='TROUSER', max_length=40),
        ),
    ]
